# Generated by Django 5.2 on 2025-04-12 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.provider'),
        ),
    ]
